export const siteConfig = {
  name: "Lokesh Yadav",
  alternateName: "Loki",
  title: "Lokesh Yadav | Full Stack Engineer",
  description:
    "Lokesh Yadav — Frontend-focused Full Stack Engineer (MERN | PERN) building production-ready, real-time web apps with React, Next.js, TypeScript, Node.js, PostgreSQL, Three.js, GSAP, WebSockets, and Redis. View projects and experience.",
  url: "https://lok1.dev",
  ogImage: "/images/portfolio.jpg",
  email: "lokeshyadv8177@gmail.com",
  phone: "+919560545070",
  keywords: [
    "lokesh yadav",
    "loki",
    "full stack engineer",
    "MERN developer",
    "PERN developer",
    "react developer",
    "next.js developer",
    "node.js developer",
    "typescript",
    "javascript",
    "three.js",
    "gsap",
    "framer motion",
    "tailwind css",
    "portfolio",
    "lok1.dev",
  ],
  author: "Lokesh Yadav",
  github: "https://github.com/lokidotdev",
  linkedin: "https://linkedin.com/in/lokidotdev/",
  twitter: "https://x.com/lokidotdev",
} as const;

export const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      "@id": `${siteConfig.url}/#person`,
      name: siteConfig.name,
      alternateName: [siteConfig.alternateName, "Lokesh", "Loki Dev"],
      jobTitle: "Full Stack Engineer",
      nationality: "Indian",
      knowsLanguage: ["en", "hi"],
      description:
        "Frontend-focused Full Stack Engineer experienced in production-ready, real-time, and performance-sensitive web applications with React, Next.js, TypeScript, and Node.js.",
      url: `${siteConfig.url}/`,
      email: siteConfig.email,
      telephone: siteConfig.phone,
      image: `${siteConfig.url}/images/portfolio-sq.png`,
      sameAs: [siteConfig.github, siteConfig.linkedin, siteConfig.twitter],
      knowsAbout: [
        "React",
        "Next.js",
        "TypeScript",
        "JavaScript",
        "Three.js",
        "GSAP",
        "Framer Motion",
        "Tailwind CSS",
        "Node.js",
        "Express.js",
        "WebSockets",
        "PostgreSQL",
        "MongoDB",
        "Redis",
        "Docker",
        "MERN Stack",
        "PERN Stack",
      ],
    },
    {
      "@type": "WebSite",
      name: "Lokesh Yadav Portfolio",
      alternateName: "Loki Portfolio",
      url: `${siteConfig.url}/`,
      description:
        "Portfolio of Lokesh Yadav — Full Stack Engineer showcasing React, Next.js, Node.js, and real-time full-stack projects.",
      publisher: { "@id": `${siteConfig.url}/#person` },
      about: { "@id": `${siteConfig.url}/#person` },
    },
  ],
};
