export const projectsList = [
  {
    name: "FOTF",
    link: "https://fotf-frontend.vercel.app",
    mobileImage: "images/fotf-600.jpg",
    desktopImage: "images/fotf.png",
    points: [
      "Developed a fully responsive animated website with smooth transitions and micro-interactions.",
      "Implemented optimized animations using GSAP for a seamless user experience.",
      "Ensured cross-browser compatibility and mobile-friendly design.",
      "Tech - React.js, GSAP, Bootstrap, HTML, CSS",
    ],
  },
  {
    name: "Prompt board",
    link: "https://promptboard.zero1studio.xyz/",
    mobileImage: "images/promptboard-600.png",
    desktopImage: "images/promptboard.png",
    points: [
      "Discover and use community-shared prompts to generate AI images",
      "Generate images and organize prompts with folders",
      "Flexible credit-based subscriptions with transparent pricing",
      "Tech - Next.js, Express.js, PostgreSQL, Node.js, razorpay, Tailwind CSS, Google Auth, Prisma",
    ],
  },
  {
    name: "ChessBlitz",
    link: "https://chessblitz.lok1.dev/",
    mobileImage: "images/chess-600.jpg",
    desktopImage: "images/chess.png",
    points: [
      "A real-time chess game application.",
      "Integrated WebSocket for seamless bi-directional communication.",
      "Tech - React.js, typescript, Node.js, WebSocket, tailwindcss, Redis, Postgresql, Prisma",
    ],
  },
  {
    name: "TriviArena",
    link: "https://triviarena.maoverse.xyz/",
    mobileImage: "images/xrc-600.jpg",
    desktopImage: "images/xrc.png",
    points: [
      "A real-time quiz application with interactive questions and live score updates.",
      "Used Firebase for authentication and real-time database functionality.",
      "Integrated WebSockets for live multiplayer quiz sessions.",
      "Tech - React.js, Express.js, MongoDB, Node.js, Firebase, Socket.io, Tailwind CSS",
    ],
  },
  {
    name: "Galaxy Generator",
    link: "https://galaxy-generator-eta.vercel.app/",
    mobileImage: "images/galaxy.png",
    desktopImage: "images/galaxy.png",
    points: [
      "A dynamic 3D galaxy generator built with Three.js using millions of particles.",
      "Customizable parameters — adjust galaxy radius, spin, branches, and color gradients in real time.",
      "Interactive camera controls and GPU-optimized rendering for smooth animations and exploration.",
      "Tech - Three.js, React.js, Vite",
    ],
  },
  {
    name: "PixelflowUI",
    link: "https://pixelflowui.lok1.dev/",
    mobileImage: "images/pixelflowui-600.png",
    desktopImage: "images/pixelflowui.png",
    points: [
      "A collection of responsive animated UI components for web applications.",
      "Open source project.",
      "Tech - Tailwind CSS, shadcn/ui, Motion, GSAP, Next.js, JavaScript",
    ],
  },
  // {
  //   name: "Gainz Journal",
  //   link: "https://gainz-journal.vercel.app",
  //   mobileImage: "images/gainz-600.png",
  //   desktopImage: "images/gainz.png",
  //   points: [
  //     "A journal app for tracking workouts and progress.",
  //     // "CQRS style architecture.",
  //     "Designed a clean and intuitive UI for better user experience.",
  //     "Tech - React.js, Express.js, MongoDB, Node.js, Google OAuth, Tailwind CSS, shadcn/ui, zod, redux",
  //   ],
  // },
  // {
  //   name: "Captionizer",
  //   link: "https://captionizer-star.vercel.app/",
  //   mobileImage: "images/captionizer-600.png",
  //   desktopImage: "images/image.png",
  //   points: [
  //     "caption generator for images with real-time text recognition.",
  //     "Utilized Machine Learning APIs to generate contextually relevant captions.",
  //     "Designed an intuitive interface for uploading and processing images efficiently.",
  //     "Tech - Next.js, MongoDB, tailwind css, AWS s3 bucket",
  //   ],
  // },
];
